# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'mlb_dbt'
version: '1.0.0'

# This setting configures which "profile" mlb_dbt uses for this project.
profile: 'mlb_dbt'

# These configurations specify where mlb_dbt should look for different types of files.
# The `model-paths` config, for mlb_api, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: [ "models" ]
analysis-paths: [ "analyses" ]
test-paths: [ "tests" ]
seed-paths: [ "seeds" ]
macro-paths: [ "macros" ]
snapshot-paths: [ "snapshots" ]

clean-targets: # directories to be removed by `mlb_dbt clean`
  - "target"
  - "dbt_packages"
  - "dbt_modules"
  - "logs"

require-dbt-version: [ ">1.0.0", "<2.0.0" ]
seeds:
  +docs:
    node_color: '#cd7f32'
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this mlb_api config, we tell mlb_dbt to build all models in the mlb_api/
# directory as views. These settings can be overridden in the individual model
# files using the `{{ config(...) }}` macro.
models:
  mlb_dbt:
    materialized: table
